version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ecto_sql
    versions:
    - 3.5.4
  - dependency-name: postgrex
    versions:
    - 0.15.8
  - dependency-name: absinthe_plug
    versions:
    - 1.5.4
  - dependency-name: credo
    versions:
    - 1.5.4
  - dependency-name: phoenix_live_view
    versions:
    - 0.15.1
  - dependency-name: ex_machina
    versions:
    - 2.5.0
